# This is a basic workflow to help you get started with Actions

name: fiap-lanches-helm

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Jonathan"
          git config user.email "jonathan.gomess1@gmail.com"

      # - name: Remove Git Tag
        
      #   run: |
      #     git tag -d lastesd-1
      #     git push origin :lastesd-1

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package chart
        run: helm package ./

      - name: Dir
        run: ls

      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Create ecr helm
        run: aws ecr create-repository --repository-name fiap-lanches-helm --region us-east-1

      - name: Auth
        run: aws ecr get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin 064829921259.dkr.ecr.us-east-1.amazonaws.com

      - name: Push helm
        run: helm push fiap-lanches-0.2.0.tgz oci://064829921259.dkr.ecr.us-east-1.amazonaws.com/fiap-lanches-helm

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.6.0
      #   with:
      #     skip_packaging: true
      #     pages_branch: gh-pages
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"     

        # Criar release com base nos charts de Helm
      # - name: Criar Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v1.0.0  # Substitua pelo nome da sua tag
      #     release_name: Release v1.0.0  # Substitua pelo nome do seu release
      #     body: Vers√£o v1.0.0 do aplicativo.  # Substitua pelo corpo do seu release
      #     draft: false
      #     prerelease: false
      #     files: ./*.tgz  # Es 